### ISSUE TITLE
打开第二个这个视频控件时报错

### ISSUE THREAD

**Issue by simdm** [835239104/KrVideoPlayerPlus#5]
再tableview的列表中打开第二个条目时，报错 （每个条目打开都会有这个控件）

<Error>: CGImageCreate: invalid image size: 0 x 0.
 -[__NSDictionaryI _postNotificationName:object:userInfo:]: unrecognized selector sent to instance 0x7fe2c25ac530

**Comment by PlutusCat** [comment]
没看明白操作步骤，请详细说明，最好能附图。

**Comment by simdm** [comment]
我发现原生36kr的也有这个问题，不用了，我已经改用别的库了，谢谢
